config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :stone_images, only: [:new, :create, :index, :show, :destroy] do
  	resource :favorites, only: [:create, :destroy]
  	resources :stone_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
  root 'stone_images#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :stone_image
end

app/models/stone_comment.rb
class StoneComment < ApplicationRecord
	belongs_to :user
	belongs_to :stone_image
end

app/models/stone_image.rb
class StoneImage < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :stone_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	validates :shop_name, presence: true
	validates :image, presence: true

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :stone_images, dependent: :destroy
  has_many :stone_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		stone_image = StoneImage.find(params[:stone_image_id])
		favorite = current_user.favorites.new(stone_image_id: stone_image.id)
		favorite.save
		redirect_to stone_image_path(stone_image)
	end

	def destroy
		stone_image = StoneImage.find(params[:stone_image_id])
		favorite = current_user.favorites.find_by(stone_image_id: stone_image.id)
		favorite.destroy
	    redirect_to stone_image_path(stone_image)
	end

end

app/controllers/stone_comments_controller.rb
class StoneCommentsController < ApplicationController
	def create
		stone_image = StoneImage.find(params[:stone_image_id])
		comment = current_user.stone_comments.new(stone_comment_params)
		comment.stone_image_id = stone_image.id
		comment.save
		redirect_to stone_image_path(stone_image)
	end

	def destroy
    StoneComment.find_by(id: params[:id], stone_image_id: params[:stone_image_id]).destroy
    redirect_to stone_image_path(params[:stone_image_id])
	end

	private
	def stone_comment_params
		params.require(:stone_comment).permit(:comment)
	end
end

app/controllers/stone_images_controller.rb
class StoneImagesController < ApplicationController

	def new
	    @stone_image = StoneImage.new
    end
    def create
    	@stone_image = StoneImage.new(stone_image_params)
    	@stone_image.user_id = current_user.id
     if @stone_image.save
         redirect_to stone_images_path
     else
         render :new
     end
    end
    def index
        @stone_images = StoneImage.page(params[:page]).reverse_order
    end
    def show
        @stone_image = StoneImage.find(params[:id])
        @stone_comment = StoneComment.new
    end

    def destroy
        @stone_image = StoneImage.find(params[:id])
        @stone_image.destroy
        redirect_to stone_images_path
    end
    private
    def stone_image_params
        params.require(:stone_image).permit(:shop_name, :image, :caption)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@stone_images = @user.stone_images.page(params[:page]).reverse_order
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to user_path(@user.id)
  end

  private
  def user_params
  	params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/stone_comments_helper.rb
module StoneCommentsHelper
end

app/helpers/stone_images_helper.rb
module StoneImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
     <meta name=”viewport” content=”width=device-width, initial-scale=1”>
    <link rel="stylesheet" href="responsive.css">

  </head>


  <body>
    <div class="head-menu">
      <ul class="menu">
        <li class="a">
          <h1>Pietra</h1>
        </li>
        <% if user_signed_in? %>
        <li class="a2">
          <%= link_to "ログアウト",destroy_user_session_path,method: :delete, :style=>"color:white;"%>
        </li>
        <li class="a2">
          <%= link_to 'マイページ', user_path(current_user.id), :style=>"color:white;" %>
        </li>
        <li class="a2">
          <%= link_to '新規投稿',new_stone_image_path, :style=>"color:white;"%>
        </li>
        <li class="a2">
          <%= link_to "投稿一覧",stone_images_path, :style=>"color:white;" %>
        </li>
      <% else %>
       <li class="a2">
        <%= link_to "新規登録", new_user_registration_path, :style=>"color:white;" %>
      </li>
      <li class="a2">
        <%= link_to "ログイン", new_user_session_path, :style=>"color:white;" %>
      </li>

        <div class="btn-trigger" id="btn">
    <span></span>
    <span></span>
    <span></span>
    </div>
    <% end %>
  </ul>
</div>
    <%= yield %>
  </body>
</html>

app/views/stone_images/index.html.erb
   <div class="image-box">
       <% @stone_images.each do |stone_image| %>
       <div class="imgtxtbox">
            <%= link_to stone_image_path(stone_image.id) do %>
            <%= attachment_image_tag stone_image, :image, :fill, 300, 300, class: "imgbox" %>
            <% end %>

             <h3 class="txtbox">
               <%= link_to stone_image_path(stone_image.id) do %>
               <%= stone_image.shop_name %>
               <% end %>
             </h3>
            <p class="txtbox"><%= stone_image.caption %></p>
            <ul class="inline-meta">
               <li class="txtbox">投稿者
                <%= stone_image.user.name %>
               </li>
               <li class="txtbox">
                 <%= link_to "#{stone_image.stone_comments.count}コメント", stone_image_path(stone_image.id) %>
               </li>
            </ul>
         </div>

            <% end %>
</div>
   <br>


   <div class="paginate">
      <%= paginate @stone_images %>
</div>

app/views/stone_images/new.html.erb
<h2 class="new-name">新規投稿</h2>

<%= form_for(@stone_image, url:stone_images_path) do |f| %>
<% if @stone_image.errors.any? %>
 	<h2 class="newbox"><%= @stone_image.errors.count %>件のエラーが発生しました。</h2>
 	<ul>
 		<% @stone_image.errors.full_messages.each do |message| %>
 		<li class="newbox"><%= message %></li>
 		<% end %>
 	</ul>
<% end %>
    <div class="new-content">
  	<%= f.attachment_field :image ,class:"newbox"%>
  </div>
    <div class="new-content">
  	 <label class="control-label sr-only">石の名前</label>
  	 <%= f.text_field :shop_name, class:"newbox", placeholder:"石の名前" %>
    </div>
    <div class="new-content">
      <%= f.text_area :caption, class:"newbox2", row:"3", placeholder:"コメント" %>
    </div>
<%= f.submit "送信",class:"new-box" %>
<% end %>

app/views/stone_images/show.html.erb
<div class="stone-image-box">

 	<%= attachment_image_tag @stone_image, :image, :fill, 500, 500, class: "post-image" %>

<div class="stone-index">
  <div class="title">
	<h2 class="post-title"><%= @stone_image.shop_name %></h2>
</div>
    <div class="caption">
    <p><%= @stone_image.caption %></p>
  </div>
	<ul>
	<li>
    <div class="image-box1">
	 投稿者<a href="#">
	 	<%= @stone_image.user.name %></a>
   </div>
	 </li>
	 <li>
    <div class="image-box1">
	 	<%= @stone_image.created_at.strftime('%Y/%m/%d') %>
   </div>
	 </li>
	 <% if @stone_image.favorited_by?(current_user) %>
	  <li>
    <div class="image-box1">
	 	<%= link_to stone_image_favorites_path(@stone_image),method: :deleate do %>
	 	<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
	 	<%= @stone_image.favorites.count %>いいね
   </div>
	 	<% end %>
	  </li>
	 	<% else %>
      <li>
        <%= link_to stone_image_favorites_path(@stone_image), method: :post do %>
        <i class="fa fa-heart-o" aria-hidden="true"></i>
        <%= @stone_image.favorites.count %>いいね
        <% end %>
     </li>
    <% end %>
	 <li>
	 	<a href="#comments"><%= @stone_image.stone_comments.count %>コメント</a>
	 </li>
   <li>
    <% if @stone_image.user == current_user %>
    <%= link_to "消去", stone_image_path(@stone_image), method: :delete %>
    <% end %>
  </li>
	</ul>
</div>
</div>

<h2 class="comment-count"><%= @stone_image.stone_comments.count %>件コメント</h2>
  <% @stone_image.stone_comments.each do |stone_comment| %>
    <li class="comment">
          <%= attachment_image_tag stone_comment.user, :profile_image, :fill, 70, 70, fallback: "sample_image.jpg", size:'70x70'%>
            <a href="#" class="link-author"><%= stone_comment.user.name %></a>
            <span class="comment-meta"><br>
              <span class="comment-date"><%= stone_comment.created_at.strftime('%Y/%m/%d') %></span>
            </span>
   <div class="comment-entry"><%= stone_comment.comment %></div>
          <% if stone_comment.user == current_user %>
   <%= link_to "削除", stone_image_stone_comment_path(stone_comment.stone_image,stone_comment), method: :delete %>
   <% end %>
    </li>
  </div>
   <% end %>


<%= form_for [@stone_image, @stone_comment] do |f| %>
 <div class="comment-box">
      <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %><br>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>

<% end %>
</div>

app/views/users/edit.html.erb
          <div class="edit-form">
          <h2 class="edit-name">プロフィール編集</h2>
          <%= form_for(@user) do |f| %>
          <div class="edit-content">
              <div class="edit-form">名前</div>
              <%= f.text_field :name, autofocus: true, class:"text-form", id:"inputName", placeholder:"名前"%>
          </div>
          <div class="edit-content">
              <%= attachment_image_tag @user, :profile_image, :fill, 130, 130, class: "text-form", fallback: "sample_image.jpg"%>
              <div class="edit-form" for="inputEmail">プロフィール画像</div>
              <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "text-form" %>
          </div>
          <div class="edit-content">
            <%= f.submit "変更を保存", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
          </div>
          <% end %>
        </div>

app/views/users/show.html.erb
<div class="profile-container">
    <h3 class="profile-name"><%= @user.name %></h3>
	<% if @user.id = current_user.id %>
	 <%= attachment_image_tag @user, :profile_image, :fill, 130, 130, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "sample_image.jpg", size:'130x130'  %>
     <% if @user.id == current_user.id %>
	<p><%= link_to "プロフィール編集", edit_user_path(@user), class: "pull-right", :style=>"color:black;"%></p>
	<% end %>
	<% end %>
</div>

 <div class="container">
   <div class="image-box">
   	 <% @stone_images.each do |stone_image| %>
       <div class="imgtxtbox">
   	  	  	<%= link_to stone_image_path(stone_image.id) do %>
   	  	  	<%= attachment_image_tag stone_image, :image, :fill, 300, 300, class: "imgbox" %>
   	  	  	<% end %>

	          <h3 class="txtbox">
   	  			<%= link_to stone_image_path(stone_image.id) do %>
   	  			<%= stone_image.shop_name %>
   	  			<% end %>
   	  		 </h3>
   	  		<p class="txtbox"><%= stone_image.caption %></p>
   	  		<ul class="inline-meta">
   	  			<li class="txtbox">By
   	  			 <%= stone_image.user.name %>
   	  			</li>
   	  			<li class="txtbox">
   	  			  <%= link_to "#{stone_image.stone_comments.count}コメント", stone_image_path(stone_image.id) %>
   	  			</li>
   	  		</ul>
         </div>
   	      <% end %>
   </div>
   </div>
      <%= paginate @stone_images %>